### ISSUE TITLE
python run.py 실행시 오류

### ISSUE THREAD

**Issue by eagleone-7** [Buddha7771/ChzzkChat#2]
안녕하세요. 개발자님
우선, 제가 코린이(비전공자)라는 점 미리 양해 부탁드립니다

VS코드에서 터미널로 python run.py 했는데 다음과 같이 오류가 뜨네요
혹시나 싶어서 깃허브에 올려주신 알집 파일을 새로 다운 받아서 설치해보기도 했습니다.
채팅 잘 올라오다가 갑자기 이렇게 떴습니다. 해결방법이 궁금합니다..

$ python run.py
Traceback (most recent call last):
  File "C:\Users\ABC\OneDrive\바탕 화면\코드\VS Code\Chzzk\ChzzkChat\run.py", line 172, in <module>
    chzzkchat = ChzzkChat(args.streamer_id, cookies, logger)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\\Users\ABC\OneDrive\바탕 화면\코드\VS Code\Chzzk\ChzzkChat\run.py", line 25, in __init__
    self.connect()
  File "\Users\ABC\OneDrive\바탕 화면\코드\VS Code\Chzzk\ChzzkChat\run.py", line 30, in connect
    sock = WebSocket()
           ^^^^^^^^^^^
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'

**Comment by Buddha7771** [comment]
miniconda로 가상환경을 만들고 websocket 라이브러리를 새로 설치하셨는지 확인 부탁드립니다.

**Comment by eagleone-7** [comment]
> miniconda로 가상환경을 만들고 websocket 라이브러리를 새로 설치하셨는지 확인 부탁드립니다.

비 전공자라 정말 죄송한데, 말씀해주신게 혹시 여기서 "# 패키지 설치"에서 말씀해주신  pip install websocket 맞을까요? 그렇다면 설치 했습니다.
 
 # 코드 다운로드
$ git clone https://github.com/Buddha7771/ChzzkChat .
$ cd ChzzkChat
=> 코드는 알집으로 다운받아서 풀었구요

# 가상환경 설치
$ conda create -n chzzk python=3.9
$ conda activate chzzk
=> 미니콘다 설치 후, 제 파이썬이 3.12.1이라서 
conda create -n chzzk python=3.12.1
source activate chzzk 했습니다

# 패키지 설치
$ pip install websocket
$ pip install websocket-client
$ pip install requests 
=> 위의 가상환경 설치까지 작업이 끝난 후 패키지에 모든 설치를 했습니다.
지금 새로 커밋해주신 파일 다운 받아서 시도해봤는데 여전히 같은 오류가 발행하고 있습니다.

$ python run.py
Traceback (most recent call last):
  File "C:\Users\ABC\OneDrive\바탕 화면\코드\VS Code\Chzzk\ChzzkChat\run.py", line 173, in <module>
    chzzkchat = ChzzkChat(args.streamer_id, cookies, logger)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\OneDrive\바탕 화면\코드\VS Code\Chzzk\ChzzkChat\run.py", line 25, in __init__
    self.connect()
  File "C:\Users\ABC\OneDrive\바탕 화면\코드\VS Code\Chzzk\ChzzkChat\run.py", line 30, in connect
    sock = WebSocket()
           ^^^^^^^^^^^
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'

**Comment by Buddha7771** [comment]
이 코드는 python 3.9 버전으로 개발된 코드입니다. 되도록 `conda create -n chzzk python=3.9` 으로 python 3.9 환경을 만들어주시기 바랍니다.

또한 계속되는 에러가 websocket 버전 문제로 보입니다. websocket 버전이 `1.7.0`이 맞는지 확인바랍니다.

**Comment by eagleone-7** [comment]
> 이 코드는 python 3.9 버전으로 개발된 코드입니다. 되도록 `conda create -n chzzk python=3.9` 으로 python 3.9 환경을 만들어주시기 바랍니다.
> 
> 또한 계속되는 에러가 websocket 버전 문제로 보입니다. websocket 버전이 `1.7.0`이 맞는지 확인바랍니다.

아! 문제 해결되었습니다. 
$ pip uninstall websocket websocket-client requests 해서 전부 삭제하고 새로 설치했습니다.
**websocket은 버전 0.2.1**
**websocket-client은 버전 1.7.0** 인것을 확인했습니다.
늦은 시간에 귀찮게 해서 정말 죄송합니다...😞🙏
