### ISSUE TITLE
버그제보

### ISSUE THREAD

**Issue by k6k71c** [Buddha7771/ChzzkChat#3]
1. 익명도네 나오면 채팅기록이 전체중단됨
2. 이모지가 채팅에 있으면 해당 채팅만 기록안됨
예시 : 😆 나무
이런식으로 있으면 이모지만 안나오는게 아니라 나무도 채팅저장안됨
3. 네이버 로그인상태로 방송시작 30분전에 대기타고 있으면 10분정도 기록되다 채팅기록이 중단됨
생방때는 채팅연달아서 제대로 기록됨

**Comment by Buddha7771** [comment]
수정하였습니다.
