### ISSUE TITLE
버그제보

### ISSUE THREAD

**Issue by k6k71c** [Buddha7771/ChzzkChat#4]
1. 방송전에 대기탈때 방송기록저장 잘되길래 켜놨는데 방송시작되면 생방채팅기록이 chat.log에 저장안됨
2. 저 버그 때문에 방송시작때 다시 돌렸는데 방송시작 전 채팅기록이 chat.log에서 사라짐
이 시점에서 생방기록은 저장잘됨, 동일방송으로만 돌렸음

**Comment by Buddha7771** [comment]
1번은 어떤 상황인지 잘 모르겠습니다. 좀 더 자세한 설명을 해주시면 감사하겠습니다.
2번은 logger 설정 때문입니다.  `logging.FileHandler('chat.log', mode = "w")`에서  `mode = "a"`로 바꾸시면 이전 기록이 사라지지 않습니다.

**Comment by k6k71c** [comment]
방송시작 전 대기시간은 채팅기록이 저장되다가 인방인이 방송켜면 채팅저장기록이 멈추는 증상이 있음
매번 그러는 건아니고 랜덤으로 나오는 상황같음

- 채팅대기시간 (cmd창)
[2024-02-04 21:41:49] 1 : 가
[2024-02-04 21:41:50] 2 : 나

- 인방인 방송켜지면 cmd창에는
AA 채팅창에 연결 중 ...
연결 완료
에서 멈춰있음

**Comment by Buddha7771** [comment]
답변이 늦었습니다. 
해당 버그는 방송 시작시 chatChannelId가 달라져 생긴 버그입니다. https://github.com/kimcore/chzzk/issues/9#issuecomment-1887733322
Ping-pong 때마다 chatChannelId를 대조하여 새로 연결하는 방식으로 해결하였습니다.
