### ISSUE TITLE
버그제보2

### ISSUE THREAD

**Issue by k6k71c** [Buddha7771/ChzzkChat#5]
구독할때 나오는 글이 기록이 안됨

**Comment by k6k71c** [comment]
구독자 도네 내용은 나오는데 일반채팅처럼 나옴

[2024-02-26 20:28:47]  A님이 89개월동안 정기구독 중입니다!
89개월 동안 팬 정기구독 중입니다!
:안녕

이런식으로 나오는게 아니고
[2024-02-26 20:28:47] A : 안녕
이런식으로 나와서 구독도네인지 구분 불가능함

**Comment by Buddha7771** [comment]
일단 일반 채팅과 후원은 구분되도록 chat_type을 추가했습니다.
하지만 구독은 메세지 내역이 없어 같아 스킵되는 것 같습니다.
