### ISSUE TITLE
 채널아이디 쳐도 프로그램 동작안됨

### ISSUE THREAD

**Issue by k6k71c** [Buddha7771/ChzzkChat#6]
2024년 3월 5일부터 채널아이디 써도 프로그램이 작동안하게 바뀜
오류내용 : Traceback (most recent call last):
  File "C:\run.py", line 189, in <module>
    chzzkchat = ChzzkChat(args.streamer_id, cookies, logger)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\run.py", line 22, in __init__
    self.channelName   = api.fetch_channelName(self.streamer)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\api.py", line 21, in fetch_channelName
 raise ValueError(f'잘못된 입력값 : {streamer}')
ValueError: 잘못된 입력값 : 9381e7d6816e6d915a44a13c0195b202

**Comment by Buddha7771** [comment]
임시 헤더를 설정해 해결했습니다
