### ISSUE TITLE
라이브러리 설치 방법 수정

### ISSUE THREAD

**Issue by Lee2532** [Buddha7771/ChzzkChat#8]
기존 README.md 방식으로 라이브러리르 설치할경우 시간에 따라 다른 버전의 라이브러리가 설치됨에 따라 오류 발생
이를 통일 하기 위해 requirements 에 버전 고정

**Comment by Buddha7771** [comment]
websocket 라이브러리에 오류가 있어 websocket-client 만 설치되도록 수정했습니다.
